package MoreOres.init;

import MoreOres.itemGroups.Armor;
import MoreOres.itemGroups.Resources;
import MoreOres.itemGroups.Tools;
import MoreOres.itemGroups.Weapons;
import MoreOres.lists.ArmorMaterialList;
import MoreOres.lists.BlockList;
import MoreOres.lists.ItemList;
import MoreOres.lists.ToolMaterialList;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.ArmorItem;
import net.minecraft.item.AxeItem;
import net.minecraft.item.BlockItem;
import net.minecraft.item.HoeItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.PickaxeItem;
import net.minecraft.item.ShovelItem;
import net.minecraft.item.SwordItem;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = "moreores", bus = Mod.EventBusSubscriber.Bus.MOD)
public class RegisterItems 
{
	public static final ItemGroup resources = new Resources();
	public static final ItemGroup tools = new Tools();
	public static final ItemGroup weapons = new Weapons();
	public static final ItemGroup armor = new Armor();
	
	//Register Items
	@SubscribeEvent
	public static void onItemsRegistry(final RegistryEvent.Register<Item> itemRegistryEvent)
	{
		itemRegistryEvent.getRegistry().registerAll
		(
			//Items
			ItemList.copper_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("copper_ingot")),
			ItemList.tin_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("tin_ingot")),
			ItemList.silver_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("silver_ingot")),
			ItemList.lead_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("lead_ingot")),
			ItemList.platinum_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("platinum_ingot")),
			ItemList.uranium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("uranium_ingot")),
			ItemList.ruby_gem = new Item(new Item.Properties().group(resources)).setRegistryName(location("ruby_gem")),
			ItemList.topaz_gem = new Item(new Item.Properties().group(resources)).setRegistryName(location("topaz_gem")),
			ItemList.cobalt_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("cobalt_ingot")),
			ItemList.ardite_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("ardite_ingot")),
			ItemList.nickel_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("nickel_ingot")),
			ItemList.netherium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("netherium_ingot")),
			ItemList.enderium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("enderium_ingot")),
			ItemList.zinc_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("zinc_ingot")),
			ItemList.titanium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("titanium_ingot")),
			ItemList.tungsten_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("tungsten_ingot")),
			ItemList.lithium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("lithium_ingot")),
			ItemList.aluminium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("aluminium_ingot")),
			ItemList.amethyst_gem = new Item(new Item.Properties().group(resources)).setRegistryName(location("amethyst_gem")),
			ItemList.sapphire_gem = new Item(new Item.Properties().group(resources)).setRegistryName(location("sapphire_gem")),
			ItemList.osmium_ingot = new Item(new Item.Properties().group(resources)).setRegistryName(location("osmium_ingot")),
			ItemList.opal_gem = new Item(new Item.Properties().group(resources)).setRegistryName(location("opal_gem")),
			//Nuggets
			ItemList.copper_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("copper_nugget")),
			ItemList.tin_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("tin_nugget")),
			ItemList.silver_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("silver_nugget")),
			ItemList.lead_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("lead_nugget")),
			ItemList.platinum_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("platinum_nugget")),
			ItemList.uranium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("uranium_nugget")),
			ItemList.cobalt_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("cobalt_nugget")),
			ItemList.ardite_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("ardite_nugget")),
			ItemList.nickel_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("nickel_nugget")),
			ItemList.netherium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("netherium_nugget")),
			ItemList.enderium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("enderium_nugget")),
			ItemList.zinc_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("zinc_nugget")),
			ItemList.titanium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("titanium_nugget")),
			ItemList.tungsten_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("tungsten_nugget")),
			ItemList.lithium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("lithium_nugget")),
			ItemList.aluminium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("aluminium_nugget")),
			ItemList.osmium_nugget = new Item(new Item.Properties().group(resources)).setRegistryName(location("osmium_nugget")),
			//Items of ItemBlocks
			ItemList.copper_block = new BlockItem(BlockList.copper_block, new Item.Properties().group(resources)).setRegistryName(BlockList.copper_block.getRegistryName()),
			ItemList.tin_block = new BlockItem(BlockList.tin_block, new Item.Properties().group(resources)).setRegistryName(BlockList.tin_block.getRegistryName()),
			ItemList.silver_block = new BlockItem(BlockList.silver_block, new Item.Properties().group(resources)).setRegistryName(BlockList.silver_block.getRegistryName()),
			ItemList.lead_block = new BlockItem(BlockList.lead_block, new Item.Properties().group(resources)).setRegistryName(BlockList.lead_block.getRegistryName()),
			ItemList.platinum_block = new BlockItem(BlockList.platinum_block, new Item.Properties().group(resources)).setRegistryName(BlockList.platinum_block.getRegistryName()),
			ItemList.uranium_block = new BlockItem(BlockList.uranium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.uranium_block.getRegistryName()),
			ItemList.ruby_block = new BlockItem(BlockList.ruby_block, new Item.Properties().group(resources)).setRegistryName(BlockList.ruby_block.getRegistryName()),
			ItemList.topaz_block = new BlockItem(BlockList.topaz_block, new Item.Properties().group(resources)).setRegistryName(BlockList.topaz_block.getRegistryName()),
			ItemList.cobalt_block = new BlockItem(BlockList.cobalt_block, new Item.Properties().group(resources)).setRegistryName(BlockList.cobalt_block.getRegistryName()),
			ItemList.ardite_block = new BlockItem(BlockList.ardite_block, new Item.Properties().group(resources)).setRegistryName(BlockList.ardite_block.getRegistryName()),
			ItemList.nickel_block = new BlockItem(BlockList.nickel_block, new Item.Properties().group(resources)).setRegistryName(BlockList.nickel_block.getRegistryName()),
			ItemList.netherium_block = new BlockItem(BlockList.netherium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.netherium_block.getRegistryName()),
			ItemList.enderium_block = new BlockItem(BlockList.enderium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.enderium_block.getRegistryName()),
			ItemList.zinc_block = new BlockItem(BlockList.zinc_block, new Item.Properties().group(resources)).setRegistryName(BlockList.zinc_block.getRegistryName()),
			ItemList.titanium_block = new BlockItem(BlockList.titanium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.titanium_block.getRegistryName()),
			ItemList.tungsten_block = new BlockItem(BlockList.tungsten_block, new Item.Properties().group(resources)).setRegistryName(BlockList.tungsten_block.getRegistryName()),
			ItemList.lithium_block = new BlockItem(BlockList.lithium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.lithium_block.getRegistryName()),
			ItemList.aluminium_block = new BlockItem(BlockList.aluminium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.aluminium_block.getRegistryName()),
			ItemList.amethyst_block = new BlockItem(BlockList.amethyst_block, new Item.Properties().group(resources)).setRegistryName(BlockList.amethyst_block.getRegistryName()),
			ItemList.sapphire_block = new BlockItem(BlockList.sapphire_block, new Item.Properties().group(resources)).setRegistryName(BlockList.sapphire_block.getRegistryName()),
			ItemList.osmium_block = new BlockItem(BlockList.osmium_block, new Item.Properties().group(resources)).setRegistryName(BlockList.osmium_block.getRegistryName()),
			ItemList.opal_block = new BlockItem(BlockList.opal_block, new Item.Properties().group(resources)).setRegistryName(BlockList.opal_block.getRegistryName()),
			//Items of Ores
			ItemList.copper_ore = new BlockItem(BlockList.copper_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.copper_ore.getRegistryName()),
			ItemList.tin_ore = new BlockItem(BlockList.tin_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.tin_ore.getRegistryName()),
			ItemList.silver_ore = new BlockItem(BlockList.silver_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.silver_ore.getRegistryName()),
			ItemList.lead_ore = new BlockItem(BlockList.lead_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.lead_ore.getRegistryName()),
			ItemList.platinum_ore = new BlockItem(BlockList.platinum_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.platinum_ore.getRegistryName()),
			ItemList.uranium_ore = new BlockItem(BlockList.uranium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.uranium_ore.getRegistryName()),
			ItemList.ruby_ore_overworld = new BlockItem(BlockList.ruby_ore_overworld, new Item.Properties().group(resources)).setRegistryName(BlockList.ruby_ore_overworld.getRegistryName()),
			ItemList.ruby_ore_nether = new BlockItem(BlockList.ruby_ore_nether, new Item.Properties().group(resources)).setRegistryName(BlockList.ruby_ore_nether.getRegistryName()),
			ItemList.topaz_ore = new BlockItem(BlockList.topaz_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.topaz_ore.getRegistryName()),
			ItemList.cobalt_ore_overworld = new BlockItem(BlockList.cobalt_ore_overworld, new Item.Properties().group(resources)).setRegistryName(BlockList.cobalt_ore_overworld.getRegistryName()),
			ItemList.cobalt_ore_nether = new BlockItem(BlockList.cobalt_ore_nether, new Item.Properties().group(resources)).setRegistryName(BlockList.cobalt_ore_nether.getRegistryName()),
			ItemList.ardite_ore = new BlockItem(BlockList.ardite_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.ardite_ore.getRegistryName()),
			ItemList.nickel_ore = new BlockItem(BlockList.nickel_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.nickel_ore.getRegistryName()),
			ItemList.netherium_ore = new BlockItem(BlockList.netherium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.netherium_ore.getRegistryName()),
			ItemList.enderium_ore = new BlockItem(BlockList.enderium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.enderium_ore.getRegistryName()),
			ItemList.zinc_ore = new BlockItem(BlockList.zinc_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.zinc_ore.getRegistryName()),
			ItemList.titanium_ore = new BlockItem(BlockList.titanium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.titanium_ore.getRegistryName()),
			ItemList.tungsten_ore = new BlockItem(BlockList.tungsten_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.tungsten_ore.getRegistryName()),
			ItemList.lithium_ore = new BlockItem(BlockList.lithium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.lithium_ore.getRegistryName()),
			ItemList.aluminium_ore = new BlockItem(BlockList.aluminium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.aluminium_ore.getRegistryName()),
			ItemList.amethyst_ore = new BlockItem(BlockList.amethyst_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.amethyst_ore.getRegistryName()),
			ItemList.sapphire_ore = new BlockItem(BlockList.sapphire_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.sapphire_ore.getRegistryName()),
			ItemList.osmium_ore = new BlockItem(BlockList.osmium_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.osmium_ore.getRegistryName()),
			ItemList.opal_ore = new BlockItem(BlockList.opal_ore, new Item.Properties().group(resources)).setRegistryName(BlockList.opal_ore.getRegistryName()),
			//Tools
			ItemList.copper_axe = new AxeItem(ToolMaterialList.COPPER, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("copper_axe")),
			ItemList.copper_pickaxe = new PickaxeItem(ToolMaterialList.COPPER, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("copper_pickaxe")),
			ItemList.copper_shovel = new ShovelItem(ToolMaterialList.COPPER, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("copper_shovel")),
			ItemList.copper_hoe = new HoeItem(ToolMaterialList.COPPER, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("copper_hoe")),
			ItemList.tin_axe = new AxeItem(ToolMaterialList.TIN, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tin_axe")),
			ItemList.tin_pickaxe = new PickaxeItem(ToolMaterialList.TIN, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tin_pickaxe")),
			ItemList.tin_shovel = new ShovelItem(ToolMaterialList.TIN, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tin_shovel")),
			ItemList.tin_hoe = new HoeItem(ToolMaterialList.TIN, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tin_hoe")),
			ItemList.silver_axe = new AxeItem(ToolMaterialList.SILVER, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("silver_axe")),
			ItemList.silver_pickaxe = new PickaxeItem(ToolMaterialList.SILVER, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("silver_pickaxe")),
			ItemList.silver_shovel = new ShovelItem(ToolMaterialList.SILVER, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("silver_shovel")),
			ItemList.silver_hoe = new HoeItem(ToolMaterialList.SILVER, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("silver_hoe")),
			ItemList.lead_axe = new AxeItem(ToolMaterialList.LEAD, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lead_axe")),
			ItemList.lead_pickaxe = new PickaxeItem(ToolMaterialList.LEAD, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lead_pickaxe")),
			ItemList.lead_shovel = new ShovelItem(ToolMaterialList.LEAD, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lead_shovel")),
			ItemList.lead_hoe = new HoeItem(ToolMaterialList.LEAD, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lead_hoe")),
			ItemList.platinum_axe = new AxeItem(ToolMaterialList.PLATINUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("platinum_axe")),
			ItemList.platinum_pickaxe = new PickaxeItem(ToolMaterialList.PLATINUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("platinum_pickaxe")),
			ItemList.platinum_shovel = new ShovelItem(ToolMaterialList.PLATINUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("platinum_shovel")),
			ItemList.platinum_hoe = new HoeItem(ToolMaterialList.PLATINUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("platinum_hoe")),
			ItemList.uranium_axe = new AxeItem(ToolMaterialList.URANIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("uranium_axe")),
			ItemList.uranium_pickaxe = new PickaxeItem(ToolMaterialList.URANIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("uranium_pickaxe")),
			ItemList.uranium_shovel = new ShovelItem(ToolMaterialList.URANIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("uranium_shovel")),
			ItemList.uranium_hoe = new HoeItem(ToolMaterialList.URANIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("uranium_hoe")),
			ItemList.ruby_axe = new AxeItem(ToolMaterialList.RUBY, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ruby_axe")),
			ItemList.ruby_pickaxe = new PickaxeItem(ToolMaterialList.RUBY, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ruby_pickaxe")),
			ItemList.ruby_shovel = new ShovelItem(ToolMaterialList.RUBY, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ruby_shovel")),
			ItemList.ruby_hoe = new HoeItem(ToolMaterialList.RUBY, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ruby_hoe")),
			ItemList.topaz_axe = new AxeItem(ToolMaterialList.TOPAZ, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("topaz_axe")),
			ItemList.topaz_pickaxe = new PickaxeItem(ToolMaterialList.TOPAZ, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("topaz_pickaxe")),
			ItemList.topaz_shovel = new ShovelItem(ToolMaterialList.TOPAZ, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("topaz_shovel")),
			ItemList.topaz_hoe = new HoeItem(ToolMaterialList.TOPAZ, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("topaz_hoe")),
			ItemList.cobalt_axe = new AxeItem(ToolMaterialList.COBALT, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("cobalt_axe")),
			ItemList.cobalt_pickaxe = new PickaxeItem(ToolMaterialList.COBALT, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("cobalt_pickaxe")),
			ItemList.cobalt_shovel = new ShovelItem(ToolMaterialList.COBALT, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("cobalt_shovel")),
			ItemList.cobalt_hoe = new HoeItem(ToolMaterialList.COBALT, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("cobalt_hoe")),
			ItemList.ardite_axe = new AxeItem(ToolMaterialList.ARDITE, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ardite_axe")),
			ItemList.ardite_pickaxe = new PickaxeItem(ToolMaterialList.ARDITE, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ardite_pickaxe")),
			ItemList.ardite_shovel = new ShovelItem(ToolMaterialList.ARDITE, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ardite_shovel")),
			ItemList.ardite_hoe = new HoeItem(ToolMaterialList.ARDITE, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("ardite_hoe")),
			ItemList.nickel_axe = new AxeItem(ToolMaterialList.NICKEL, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("nickel_axe")),
			ItemList.nickel_pickaxe = new PickaxeItem(ToolMaterialList.NICKEL, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("nickel_pickaxe")),
			ItemList.nickel_shovel = new ShovelItem(ToolMaterialList.NICKEL, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("nickel_shovel")),
			ItemList.nickel_hoe = new HoeItem(ToolMaterialList.NICKEL, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("nickel_hoe")),
			ItemList.netherium_axe = new AxeItem(ToolMaterialList.NETHERIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("netherium_axe")),
			ItemList.netherium_pickaxe = new PickaxeItem(ToolMaterialList.NETHERIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("netherium_pickaxe")),
			ItemList.netherium_shovel = new ShovelItem(ToolMaterialList.NETHERIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("netherium_shovel")),
			ItemList.netherium_hoe = new HoeItem(ToolMaterialList.NETHERIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("netherium_hoe")),
			ItemList.enderium_axe = new AxeItem(ToolMaterialList.ENDERIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("enderium_axe")),
			ItemList.enderium_pickaxe = new PickaxeItem(ToolMaterialList.ENDERIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("enderium_pickaxe")),
			ItemList.enderium_shovel = new ShovelItem(ToolMaterialList.ENDERIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("enderium_shovel")),
			ItemList.enderium_hoe = new HoeItem(ToolMaterialList.ENDERIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("enderium_hoe")),
			ItemList.zinc_axe = new AxeItem(ToolMaterialList.ZINC, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("zinc_axe")),
			ItemList.zinc_pickaxe = new PickaxeItem(ToolMaterialList.ZINC, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("zinc_pickaxe")),
			ItemList.zinc_shovel = new ShovelItem(ToolMaterialList.ZINC, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("zinc_shovel")),
			ItemList.zinc_hoe = new HoeItem(ToolMaterialList.ZINC, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("zinc_hoe")),
			ItemList.titanium_axe = new AxeItem(ToolMaterialList.TITANIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("titanium_axe")),
			ItemList.titanium_pickaxe = new PickaxeItem(ToolMaterialList.TITANIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("titanium_pickaxe")),
			ItemList.titanium_shovel = new ShovelItem(ToolMaterialList.TITANIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("titanium_shovel")),
			ItemList.titanium_hoe = new HoeItem(ToolMaterialList.TITANIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("titanium_hoe")),
			ItemList.tungsten_axe = new AxeItem(ToolMaterialList.TUNGSTEN, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tungsten_axe")),
			ItemList.tungsten_pickaxe = new PickaxeItem(ToolMaterialList.TUNGSTEN, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tungsten_pickaxe")),
			ItemList.tungsten_shovel = new ShovelItem(ToolMaterialList.TUNGSTEN, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tungsten_shovel")),
			ItemList.tungsten_hoe = new HoeItem(ToolMaterialList.TUNGSTEN, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("tungsten_hoe")),
			ItemList.lithium_axe = new AxeItem(ToolMaterialList.LITHIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lithium_axe")),
			ItemList.lithium_pickaxe = new PickaxeItem(ToolMaterialList.LITHIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lithium_pickaxe")),
			ItemList.lithium_shovel = new ShovelItem(ToolMaterialList.LITHIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lithium_shovel")),
			ItemList.lithium_hoe = new HoeItem(ToolMaterialList.LITHIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("lithium_hoe")),
			ItemList.aluminium_axe = new AxeItem(ToolMaterialList.ALUMINIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("aluminium_axe")),
			ItemList.aluminium_pickaxe = new PickaxeItem(ToolMaterialList.ALUMINIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("aluminium_pickaxe")),
			ItemList.aluminium_shovel = new ShovelItem(ToolMaterialList.ALUMINIUM, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("aluminium_shovel")),
			ItemList.aluminium_hoe = new HoeItem(ToolMaterialList.ALUMINIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("aluminium_hoe")),
			ItemList.amethyst_axe = new AxeItem(ToolMaterialList.AMETHYST, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("amethyst_axe")),
			ItemList.amethyst_pickaxe = new PickaxeItem(ToolMaterialList.AMETHYST, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("amethyst_pickaxe")),
			ItemList.amethyst_shovel = new ShovelItem(ToolMaterialList.AMETHYST, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("amethyst_shovel")),
			ItemList.amethyst_hoe = new HoeItem(ToolMaterialList.AMETHYST, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("amethyst_hoe")),
			ItemList.sapphire_axe = new AxeItem(ToolMaterialList.SAPPHIRE, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("sapphire_axe")),
			ItemList.sapphire_pickaxe = new PickaxeItem(ToolMaterialList.SAPPHIRE, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("sapphire_pickaxe")),
			ItemList.sapphire_shovel = new ShovelItem(ToolMaterialList.SAPPHIRE, -3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("sapphire_shovel")),
			ItemList.sapphire_hoe = new HoeItem(ToolMaterialList.SAPPHIRE, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("sapphire_hoe")),
			ItemList.osmium_axe = new AxeItem(ToolMaterialList.OSMIUM, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("osmium_axe")),
			ItemList.osmium_pickaxe = new PickaxeItem(ToolMaterialList.OSMIUM, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("osmium_pickaxe")),
			ItemList.osmium_shovel = new ShovelItem(ToolMaterialList.OSMIUM, - 3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("osmium_shovel")),
			ItemList.osmium_hoe = new HoeItem(ToolMaterialList.OSMIUM, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("osmium_hoe")),
			ItemList.opal_axe = new AxeItem(ToolMaterialList.OPAL, -1.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("opal_axe")),
			ItemList.opal_pickaxe = new PickaxeItem(ToolMaterialList.OPAL, -2, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("opal_pickaxe")),
			ItemList.opal_shovel = new ShovelItem(ToolMaterialList.OPAL, - 3.0f, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("opal_shovel")),
			ItemList.opal_hoe = new HoeItem(ToolMaterialList.OPAL, -4, 6.0f, new Item.Properties().group(tools)).setRegistryName(location("opal_hoe")),
			//Weapons
			ItemList.copper_sword = new SwordItem(ToolMaterialList.COPPER, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("copper_sword")),
			ItemList.tin_sword = new SwordItem(ToolMaterialList.TIN, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("tin_sword")),
			ItemList.silver_sword = new SwordItem(ToolMaterialList.SILVER, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("silver_sword")),
			ItemList.lead_sword = new SwordItem(ToolMaterialList.LEAD, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("lead_sword")),
			ItemList.platinum_sword = new SwordItem(ToolMaterialList.PLATINUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("platinum_sword")),
			ItemList.uranium_sword = new SwordItem(ToolMaterialList.URANIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("uranium_sword")),
			ItemList.ruby_sword = new SwordItem(ToolMaterialList.RUBY, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("ruby_sword")),
			ItemList.topaz_sword = new SwordItem(ToolMaterialList.TOPAZ, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("topaz_sword")),
			ItemList.cobalt_sword = new SwordItem(ToolMaterialList.COBALT, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("cobalt_sword")),
			ItemList.ardite_sword = new SwordItem(ToolMaterialList.ARDITE, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("ardite_sword")),
			ItemList.nickel_sword = new SwordItem(ToolMaterialList.NICKEL, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("nickel_sword")),
			ItemList.netherium_sword = new SwordItem(ToolMaterialList.NETHERIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("netherium_sword")),
			ItemList.enderium_sword = new SwordItem(ToolMaterialList.ENDERIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("enderium_sword")),
			ItemList.zinc_sword = new SwordItem(ToolMaterialList.ZINC, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("zinc_sword")),
			ItemList.titanium_sword = new SwordItem(ToolMaterialList.TITANIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("titanium_sword")),
			ItemList.tungsten_sword = new SwordItem(ToolMaterialList.TUNGSTEN, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("tungsten_sword")),
			ItemList.lithium_sword = new SwordItem(ToolMaterialList.LITHIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("lithium_sword")),
			ItemList.aluminium_sword = new SwordItem(ToolMaterialList.ALUMINIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("aluminium_sword")),
			ItemList.amethyst_sword = new SwordItem(ToolMaterialList.AMETHYST, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("amethyst_sword")),
			ItemList.sapphire_sword = new SwordItem(ToolMaterialList.SAPPHIRE, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("sapphire_sword")),
			ItemList.osmium_sword = new SwordItem(ToolMaterialList.OSMIUM, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("osmium_sword")),
			ItemList.opal_sword = new SwordItem(ToolMaterialList.OPAL, 0, 6.0f, new Item.Properties().group(weapons)).setRegistryName(location("opal_sword")),
			//Armor
			ItemList.copper_helmet = new ArmorItem(ArmorMaterialList.COPPER, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("copper_helmet")),
			ItemList.copper_chestplate = new ArmorItem(ArmorMaterialList.COPPER, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("copper_chestplate")),
			ItemList.copper_leggings = new ArmorItem(ArmorMaterialList.COPPER, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("copper_leggings")),
			ItemList.copper_boots = new ArmorItem(ArmorMaterialList.COPPER, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("copper_boots")),
			ItemList.tin_helmet = new ArmorItem(ArmorMaterialList.TIN, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("tin_helmet")),
			ItemList.tin_chestplate = new ArmorItem(ArmorMaterialList.TIN, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("tin_chestplate")),
			ItemList.tin_leggings = new ArmorItem(ArmorMaterialList.TIN, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("tin_leggings")),
			ItemList.tin_boots = new ArmorItem(ArmorMaterialList.TIN, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("tin_boots")),
			ItemList.silver_helmet = new ArmorItem(ArmorMaterialList.SILVER, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("silver_helmet")),
			ItemList.silver_chestplate = new ArmorItem(ArmorMaterialList.SILVER, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("silver_chestplate")),
			ItemList.silver_leggings = new ArmorItem(ArmorMaterialList.SILVER, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("silver_leggings")),
			ItemList.silver_boots = new ArmorItem(ArmorMaterialList.SILVER, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("silver_boots")),
			ItemList.lead_helmet = new ArmorItem(ArmorMaterialList.LEAD, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("lead_helmet")),
			ItemList.lead_chestplate = new ArmorItem(ArmorMaterialList.LEAD, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("lead_chestplate")),
			ItemList.lead_leggings = new ArmorItem(ArmorMaterialList.LEAD, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("lead_leggings")),
			ItemList.lead_boots = new ArmorItem(ArmorMaterialList.LEAD, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("lead_boots")),
			ItemList.platinum_helmet = new ArmorItem(ArmorMaterialList.PLATINUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("platinum_helmet")),
			ItemList.platinum_chestplate = new ArmorItem(ArmorMaterialList.PLATINUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("platinum_chestplate")),
			ItemList.platinum_leggings = new ArmorItem(ArmorMaterialList.PLATINUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("platinum_leggings")),
			ItemList.platinum_boots = new ArmorItem(ArmorMaterialList.PLATINUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("platinum_boots")),
			ItemList.uranium_helmet = new ArmorItem(ArmorMaterialList.URANIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("uranium_helmet")),
			ItemList.uranium_chestplate = new ArmorItem(ArmorMaterialList.URANIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("uranium_chestplate")),
			ItemList.uranium_leggings = new ArmorItem(ArmorMaterialList.URANIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("uranium_leggings")),
			ItemList.uranium_boots = new ArmorItem(ArmorMaterialList.URANIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("uranium_boots")),
			ItemList.ruby_helmet = new ArmorItem(ArmorMaterialList.RUBY, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("ruby_helmet")),
			ItemList.ruby_chestplate = new ArmorItem(ArmorMaterialList.RUBY, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("ruby_chestplate")),
			ItemList.ruby_leggings = new ArmorItem(ArmorMaterialList.RUBY, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("ruby_leggings")),
			ItemList.ruby_boots = new ArmorItem(ArmorMaterialList.RUBY, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("ruby_boots")),
			ItemList.topaz_helmet = new ArmorItem(ArmorMaterialList.TOPAZ, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("topaz_helmet")),
			ItemList.topaz_chestplate = new ArmorItem(ArmorMaterialList.TOPAZ, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("topaz_chestplate")),
			ItemList.topaz_leggings = new ArmorItem(ArmorMaterialList.TOPAZ, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("topaz_leggings")),
			ItemList.topaz_boots = new ArmorItem(ArmorMaterialList.TOPAZ, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("topaz_boots")),
			ItemList.cobalt_helmet = new ArmorItem(ArmorMaterialList.COBALT, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("cobalt_helmet")),
			ItemList.cobalt_chestplate = new ArmorItem(ArmorMaterialList.COBALT, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("cobalt_chestplate")),
			ItemList.cobalt_leggings = new ArmorItem(ArmorMaterialList.COBALT, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("cobalt_leggings")),
			ItemList.cobalt_boots = new ArmorItem(ArmorMaterialList.COBALT, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("cobalt_boots")),
			ItemList.ardite_helmet = new ArmorItem(ArmorMaterialList.ARDITE, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("ardite_helmet")),
			ItemList.ardite_chestplate = new ArmorItem(ArmorMaterialList.ARDITE, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("ardite_chestplate")),
			ItemList.ardite_leggings = new ArmorItem(ArmorMaterialList.ARDITE, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("ardite_leggings")),
			ItemList.ardite_boots = new ArmorItem(ArmorMaterialList.ARDITE, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("ardite_boots")),
			ItemList.nickel_helmet = new ArmorItem(ArmorMaterialList.NICKEL, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("nickel_helmet")),
			ItemList.nickel_chestplate = new ArmorItem(ArmorMaterialList.NICKEL, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("nickel_chestplate")),
			ItemList.nickel_leggings = new ArmorItem(ArmorMaterialList.NICKEL, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("nickel_leggings")),
			ItemList.nickel_boots = new ArmorItem(ArmorMaterialList.NICKEL, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("nickel_boots")),
			ItemList.netherium_helmet = new ArmorItem(ArmorMaterialList.NETHERIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("netherium_helmet")),
			ItemList.netherium_chestplate = new ArmorItem(ArmorMaterialList.NETHERIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("netherium_chestplate")),
			ItemList.netherium_leggings = new ArmorItem(ArmorMaterialList.NETHERIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("netherium_leggings")),
			ItemList.netherium_boots = new ArmorItem(ArmorMaterialList.NETHERIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("netherium_boots")),
			ItemList.enderium_helmet = new ArmorItem(ArmorMaterialList.ENDERIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("enderium_helmet")),
			ItemList.enderium_chestplate = new ArmorItem(ArmorMaterialList.ENDERIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("enderium_chestplate")),
			ItemList.enderium_leggings = new ArmorItem(ArmorMaterialList.ENDERIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("enderium_leggings")),
			ItemList.enderium_boots = new ArmorItem(ArmorMaterialList.ENDERIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("enderium_boots")),
			ItemList.zinc_helmet = new ArmorItem(ArmorMaterialList.ZINC, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("zinc_helmet")),
			ItemList.zinc_chestplate = new ArmorItem(ArmorMaterialList.ZINC, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("zinc_chestplate")),
			ItemList.zinc_leggings = new ArmorItem(ArmorMaterialList.ZINC, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("zinc_leggings")),
			ItemList.zinc_boots = new ArmorItem(ArmorMaterialList.ZINC, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("zinc_boots")),
			ItemList.titanium_helmet = new ArmorItem(ArmorMaterialList.TITANIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("titanium_helmet")),
			ItemList.titanium_chestplate = new ArmorItem(ArmorMaterialList.TITANIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("titanium_chestplate")),
			ItemList.titanium_leggings = new ArmorItem(ArmorMaterialList.TITANIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("titanium_leggings")),
			ItemList.titanium_boots = new ArmorItem(ArmorMaterialList.TITANIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("titanium_boots")),
			ItemList.tungsten_helmet = new ArmorItem(ArmorMaterialList.TUNGSTEN, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("tungsten_helmet")),
			ItemList.tungsten_chestplate = new ArmorItem(ArmorMaterialList.TUNGSTEN, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("tungsten_chestplate")),
			ItemList.tungsten_leggings = new ArmorItem(ArmorMaterialList.TUNGSTEN, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("tungsten_leggings")),
			ItemList.tungsten_boots = new ArmorItem(ArmorMaterialList.TUNGSTEN, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("tungsten_boots")),
			ItemList.lithium_helmet = new ArmorItem(ArmorMaterialList.LITHIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("lithium_helmet")),
			ItemList.lithium_chestplate = new ArmorItem(ArmorMaterialList.LITHIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("lithium_chestplate")),
			ItemList.lithium_leggings = new ArmorItem(ArmorMaterialList.LITHIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("lithium_leggings")),
			ItemList.lithium_boots = new ArmorItem(ArmorMaterialList.LITHIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("lithium_boots")),
			ItemList.aluminium_helmet = new ArmorItem(ArmorMaterialList.ALUMINIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("aluminium_helmet")),
			ItemList.aluminium_chestplate = new ArmorItem(ArmorMaterialList.ALUMINIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("aluminium_chestplate")),
			ItemList.aluminium_leggings = new ArmorItem(ArmorMaterialList.ALUMINIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("aluminium_leggings")),
			ItemList.aluminium_boots = new ArmorItem(ArmorMaterialList.ALUMINIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("aluminium_boots")),
			ItemList.amethyst_helmet = new ArmorItem(ArmorMaterialList.AMETHYST, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("amethyst_helmet")),
			ItemList.amethyst_chestplate = new ArmorItem(ArmorMaterialList.AMETHYST, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("amethyst_chestplate")),
			ItemList.amethyst_leggings = new ArmorItem(ArmorMaterialList.AMETHYST, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("amethyst_leggings")),
			ItemList.amethyst_boots = new ArmorItem(ArmorMaterialList.AMETHYST, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("amethyst_boots")),
			ItemList.sapphire_helmet = new ArmorItem(ArmorMaterialList.SAPPHIRE, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("sapphire_helmet")),
			ItemList.sapphire_chestplate = new ArmorItem(ArmorMaterialList.SAPPHIRE, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("sapphire_chestplate")),
			ItemList.sapphire_leggings = new ArmorItem(ArmorMaterialList.SAPPHIRE, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("sapphire_leggings")),
			ItemList.sapphire_boots = new ArmorItem(ArmorMaterialList.SAPPHIRE, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("sapphire_boots")),
			ItemList.osmium_helmet = new ArmorItem(ArmorMaterialList.OSMIUM, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("osmium_helmet")),
			ItemList.osmium_chestplate = new ArmorItem(ArmorMaterialList.OSMIUM, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("osmium_chestplate")),
			ItemList.osmium_leggings = new ArmorItem(ArmorMaterialList.OSMIUM, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("osmium_leggings")),
			ItemList.osmium_boots = new ArmorItem(ArmorMaterialList.OSMIUM, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("osmium_boots")),
			ItemList.opal_helmet = new ArmorItem(ArmorMaterialList.OPAL, EquipmentSlotType.HEAD, new Item.Properties().group(armor)).setRegistryName(location("opal_helmet")),
			ItemList.opal_chestplate = new ArmorItem(ArmorMaterialList.OPAL, EquipmentSlotType.CHEST, new Item.Properties().group(armor)).setRegistryName(location("opal_chestplate")),
			ItemList.opal_leggings = new ArmorItem(ArmorMaterialList.OPAL, EquipmentSlotType.LEGS, new Item.Properties().group(armor)).setRegistryName(location("opal_leggings")),
			ItemList.opal_boots = new ArmorItem(ArmorMaterialList.OPAL, EquipmentSlotType.FEET, new Item.Properties().group(armor)).setRegistryName(location("opal_boots"))
		);
	}
	private static ResourceLocation location(String name) 
	{
		return new ResourceLocation("moreores", name);
	}
}
